# Generated by Django 3.2.4 on 2021-06-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210619_1444'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
