# Generated by Django 3.2.4 on 2021-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='region',
            field=models.CharField(default='Uzbekistan', max_length=100),
        ),
    ]
