# Generated by Django 3.2.4 on 2021-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
