# Generated by Django 3.2.4 on 2021-06-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20210622_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
    ]
