# Generated by Django 3.2.4 on 2021-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210619_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
